CARRIER = "ship1"
BATTLESHIP = "ship2"
CRUISER = "ship3"
SUBMARINE = "ship4"
DESTROYER = "ship5"

EMPTY_CELL = 0
SHIP_CELL = 1
HIT_CELL = 2
MISS_CELL = 3
SUNK_CELL = 4

PLAYER = 100
COMPUTER = 101

VERTICAL = 10
HORIZONTAL = 11

SHIPS_NAMES_DICTIONARY = {CARRIER: "Carrier", BATTLESHIP: "Battleship", CRUISER: "Cruiser", SUBMARINE: "Submarine",
                          DESTROYER: "Destroyer"}
SHIPS_LENGTH_DICTIONARY = {CARRIER: 5, BATTLESHIP: 4, CRUISER: 3, SUBMARINE: 3, DESTROYER: 2}
ORIENTATION_DICTIONARY = {1: "horizontal", 2: "vertical"}
PLAYER_BOARD_SIGNS_DICTIONARY = {EMPTY_CELL: "o", SHIP_CELL: "S", HIT_CELL: "X", MISS_CELL: ".", SUNK_CELL: "u"}
COMPUTER_BOARD_SIGNS_DICTIONARY = {EMPTY_CELL: "o", SHIP_CELL: "o", HIT_CELL: "X", MISS_CELL: ".", SUNK_CELL: "u"}
UNHIDDEN_BOARD_SIGNS_DICTIONARY = {EMPTY_CELL: "o", SHIP_CELL: "S", HIT_CELL: "X", MISS_CELL: ".", SUNK_CELL: "u"}